default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USER'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>

development:
  <<: *default
  database: forkify_backend_development

test:
  <<: *default
  database: forkify_backend_test

production:
  <<: *default
  database: forkify_backend_production
  username: forkify_backend
  password: <%= ENV['FORKIFY_BACKEND_DATABASE_PASSWORD'] %>
